version: "3.8"

services:
  osrm-backend:
    image: osrm/osrm-backend
    container_name: osrm-backend
    volumes:
      - ./data:/data
    command: >
      osrm-routed
      --algorithm mld
      /data/map.osrm
    ports:
      - "7000:5000"
